---
output: html_document
---
<!-- create activity2.html -->

Use the controls below the spectrum to explore how the choice of slit width, response time, and scan rate affects the absorbance spectrum for a sample that consists of benzene dissolved in methanol. Changing any one variable updates the experimental spectrum. The standard spectrum from Activity 1, which was collected using a slit width of 1.0 nm, a response time of 0.3 s, and a scan rate of 5.0 nm/min, is shown as an overlay. All spectra were recorded on the same sample.

For each of the three variables, describe how a change in its value affects the spectrum. Consider effects such as the amount of noise in the spectrum, the location of a peak along the x-axis, the shape and width of a peak, and the maximum absorbance for a peak. Be sure to explore the interaction between variables; for example, is the effect of a change in slit width different when the response time is larger (2.0 or 10.0 s) or smaller (0.1 or 0.5 s)? Give some consideration to how time affects a spectrum, both in terms of scan rate and response time. If you have ideas on how the slit width, the response time, and/or the scan rate affects a spectrum, then jot them down as well.

After gathering data, summarize your observations in the form of a list. Here is an entry to get you started:

* There is a lot of noise in the spectra when the slit width is 0.25 nm, particularly for shorter wavelengths of light.

When your summary is complete, suggest an optimal set of values for the slit width, the response time, and the scan rate, and then proceed to the next activity.
