---
output: html_document
---

<!-- create about.html -->

The figure on the upper right is an illustration of a scanning monochromator. Light enters the monochromator through an entrance slit and a collimating mirror focuses the light on a diffraction grating that spreads the light out in space. A focusing mirror directs the light to an exit slit that passes it along to the detector. Rotating the diffraction grating allows different wavelengths of light to sequentially exit the monochromator and reach the detector; this what it means to scan the monochromator. 

When we use a scanning monochromator to record an absorbance spectrum, the quality of the result is affected by several experimental factors, three of which we explore in this unit.

**Slit Width**. The slit width determines the range of wavelengths, $\Delta \lambda$, in nanometers, that exit the monochromator. If the monochromator is set to a wavelength of 250 nm and the exit and the entrance slits have widths of 1.0 nm, then the exit slit passes light with wavelengths between 249 nm and 251 nm with the greatest intensity at 250 nm and with intensity approaching zero at 249 nm and 251 nm. A smaller slit width also reduces the amount of light that passes through the monochomator.

*Note. A slit width of 1.0 nm does not mean that the physical slit is 1.0 nm wide. As seen in the photograph on the lower right, a slit consists of two metal plates that are aligned to form a rectangular opening with a width on the scale of millimeters, not nanometers. The diffraction grating spreads out the light on the order of approximately 0.1--10 nm per mm; the product of this value and the width of the slit in mm gives the slit width in nm. *

**Response Time**. The response time is a measure of how long it takes the spectrometer to respond to a change in absorbance. A smaller response time corresponds to a faster response. 

*Note. There is no single way to report response times, although the time it takes for an instrument to reach 63% of its expected value is a common choice. For the instrument in this unit, the response time is defined as the time it takes to reach 98% of its expected value.* 

**Scan Rate**. The scan rate is a measure of how quickly the diffraction grating is rotated and, therefore, the rate at which light passes over the exit slit in nanometers per minute.
